### ISSUE TITLE
annoying phpfastcache instance notice

### ISSUE THREAD

**Issue by inkrement** [postaddictme/instagram-php-scraper#105]
I get the following notice from time to time:

```
PHP Notice:  [Files] Calling many times CacheManager::getInstance() for already instanced drivers is a bad practice and have a significant impact on performances.
           See https://github.com/PHPSocialNetwork/phpfastcache/wiki/[V5]-Why-calling-getInstance%28%29-each-time-is-a-bad-practice-%3F in /home/chris/instagram/vendor/phpfastcache/phpfastcache/src/phpFastCache/CacheManager.php on line 120
not able to create a instagram connection
```

**Comment by raiym** [comment]
Are you sure that you use last version of the library?
Because I think I fixed this issue back then

**Comment by inkrement** [comment]
Might be the case. I'll update it, close this issue and reopen it, if it occurs again :)

**Comment by inkrement** [comment]
Ok, this error still exists in the latest stable composer/packagist version.

**Comment by inkrement** [comment]
it was my fault. I opened it multiple times
